newspaper/urls.py
from django.urls import path

from newspaper.views import (
    index,
    NewspaperListView,
    RedactorListView,
    TopicListView,
    NewspaperDetailView,
    RedactorDetailView,
    NewspaperCreateView,
    TopicCreateView,
    RedactorCreateView,
    TopicUpdateView,
    TopicDeleteView,
    NewspaperUpdateView,
    NewspaperDeleteView,
    RedactorUpdateView,
    RedactorDeleteView,
    toggle_assign_to_newspapers,
    in_development,
)

urlpatterns = [
    path("", index, name="index"),
    path("in-development/", in_development, name="in-development"),
    path("newspapers/", NewspaperListView.as_view(), name="newspaper-list"),
    path("redactors/", RedactorListView.as_view(), name="redactor-list"),
    path("topics/", TopicListView.as_view(), name="topic-list"),
    path(
        "newspapers/<int:pk>/", NewspaperDetailView.as_view(), name="newspaper-detail"
    ),
    path("redactors/<int:pk>/", RedactorDetailView.as_view(), name="redactor-detail"),
    path(
        "newspapers/create/",
        NewspaperCreateView.as_view(),
        name="newspaper-create",
    ),
    path(
        "newspapers/<int:pk>/update/",
        NewspaperUpdateView.as_view(),
        name="newspaper-update",
    ),
    path(
        "newspapers/<int:pk>/delete/",
        NewspaperDeleteView.as_view(),
        name="newspaper-delete",
    ),
    path(
        "topics/create/",
        TopicCreateView.as_view(),
        name="topic-create",
    ),
    path(
        "topics/<int:pk>/update/",
        TopicUpdateView.as_view(),
        name="topic-update",
    ),
    path(
        "topics/<int:pk>/delete/",
        TopicDeleteView.as_view(),
        name="topic-delete",
    ),
    path(
        "redactors/create/",
        RedactorCreateView.as_view(),
        name="redactor-create",
    ),
    path(
        "redactors/<int:pk>/update/",
        RedactorUpdateView.as_view(),
        name="redactor-update",
    ),
    path(
        "redactors/<int:pk>/delete/",
        RedactorDeleteView.as_view(),
        name="redactor-delete",
    ),
    path(
        "newspapers/<int:pk>/toggle-assign/",
        toggle_assign_to_newspapers,
        name="toggle-newspaper-assign",
    ),
]

app_name = "newspaper"

newspaper_agency/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("newspaper.urls", namespace="newspaper")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

newspaper/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse


class Topic(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return f"{self.name}"


class Redactor(AbstractUser):
    years_of_experience = models.IntegerField(default=0)

    class Meta:
        verbose_name = "redactor"
        verbose_name_plural = "redactors"

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"

    def get_absolute_url(self):
        return reverse("newspaper:redactor-detail", kwargs={"pk": self.pk})


class Newspaper(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    published_date = models.DateField(auto_now_add=True)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    publisher = models.ManyToManyField(Redactor, related_name="newspapers")

    def __str__(self):
        return self.title

newspaper/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.core.exceptions import ValidationError

from newspaper.models import Redactor, Newspaper


class NewspaperForm(forms.ModelForm):
    publisher = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Newspaper
        fields = "__all__"


class RedactorCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Redactor
        fields = UserCreationForm.Meta.fields + (
            "first_name",
            "last_name",
            "email",
            "years_of_experience",
        )

    def clean_years_of_experience(self):
        return validate_years_of_experience(self.cleaned_data["years_of_experience"])


class RedactorInfoUpdateForm(forms.ModelForm):
    class Meta:
        model = Redactor
        fields = ["years_of_experience", "email"]

    def clean_years_of_experience(self):
        return validate_years_of_experience(self.cleaned_data["years_of_experience"])


def validate_years_of_experience(years_of_experience):
    if years_of_experience < 0:
        raise ValidationError("Years of experience cannot be negative")
    return years_of_experience


class NewspaperSearchForm(forms.Form):
    title = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by title"}),
    )


class TopicSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name"}),
    )


class RedactorSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by username"}),
    )

newspaper/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from .forms import (
    RedactorCreationForm,
    RedactorInfoUpdateForm,
    NewspaperForm,
    NewspaperSearchForm,
    TopicSearchForm,
    RedactorSearchForm,
)
from .models import Topic, Redactor, Newspaper


def index(request):
    num_redactors = Redactor.objects.count()
    num_newspapers = Newspaper.objects.count()
    num_topics = Topic.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_redactors": num_redactors,
        "num_newspapers": num_newspapers,
        "num_topics": num_topics,
        "num_visits": num_visits + 1,
    }

    return render(request, "newspaper/index.html", context=context)


def in_development(request):
    return render(request, "newspaper/in_development.html")


class NewspaperListView(LoginRequiredMixin, generic.ListView):
    model = Newspaper
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(NewspaperListView, self).get_context_data(**kwargs)

        title = self.request.GET.get("title", "")

        context["search_form"] = NewspaperSearchForm(initial={"title": title})

        return context

    def get_queryset(self):
        queryset = Newspaper.objects.select_related("topic")

        form = NewspaperSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(title__icontains=form.cleaned_data["title"])

        return queryset


class NewspaperDetailView(LoginRequiredMixin, generic.DetailView):
    model = Newspaper


class NewspaperCreateView(LoginRequiredMixin, generic.CreateView):
    model = Newspaper
    form_class = NewspaperForm
    success_url = reverse_lazy("newspaper:newspaper-list")


class NewspaperUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Newspaper
    form_class = NewspaperForm
    success_url = reverse_lazy("newspaper:newspaper-list")


class NewspaperDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Newspaper
    success_url = reverse_lazy("newspaper:newspaper-list")


class RedactorListView(LoginRequiredMixin, generic.ListView):
    model = Redactor
    context_object_name = "redactor_list"
    template_name = "newspaper/redactor_list.html"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(RedactorListView, self).get_context_data(**kwargs)

        username = self.request.GET.get("username", "")

        context["search_form"] = RedactorSearchForm(initial={"username": username})
        return context

    def get_queryset(self):
        queryset = Redactor.objects.all()

        form = RedactorSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(username__icontains=form.cleaned_data["username"])
        return queryset


class RedactorDetailView(LoginRequiredMixin, generic.DetailView):
    model = Redactor
    queryset = Redactor.objects.prefetch_related("newspapers__publisher")


class RedactorCreateView(LoginRequiredMixin, generic.CreateView):
    model = Redactor
    form_class = RedactorCreationForm


class RedactorUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Redactor
    form_class = RedactorInfoUpdateForm
    success_url = reverse_lazy("newspaper:redactor-list")


class RedactorDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Redactor
    success_url = reverse_lazy("newspaper:redactor-list")


class TopicListView(LoginRequiredMixin, generic.ListView):
    model = Topic
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TopicListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")

        context["search_form"] = TopicSearchForm(initial={"name": name})
        return context

    def get_queryset(self):
        queryset = Topic.objects.all()

        form = TopicSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset


class TopicCreateView(LoginRequiredMixin, generic.CreateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("newspaper:topic-list")


class TopicUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("newspaper:topic-list")


class TopicDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Topic
    success_url = reverse_lazy("newspaper:topic-list")


@login_required
def toggle_assign_to_newspapers(request, pk):
    redactor = Redactor.objects.get(id=request.user.id)
    if Newspaper.objects.get(id=pk) in redactor.newspapers.all():
        redactor.newspapers.remove(pk)
    else:
        redactor.newspapers.add(pk)
    return HttpResponseRedirect(reverse_lazy("newspaper:newspaper-detail", args=[pk]))

templates/newspaper/in_development.html
{% extends "base-presentation.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container py-2">
    <h1>
      Currently in development
    </h1>
  </div>
{% endblock %}

templates/newspaper/index.html
{% extends "base-presentation.html" %}

{% block title %} Presentation {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %} index-page {% endblock body_class %}

{% block content %}

  <header class="header-2">
    <div class="page-header section-height-75 relative" style="background-image: url('{{ ASSETS_ROOT }}/img/curved-images/curved55.jpg')">
      <div class="container">
        <div class="row">
          <div class="col-lg-7 text-center mx-auto">
            <h1 class="text-white pt-3 mt-n5">
              <a class="text-gradient text-info" target="_blank"
                 href="https://appseed.us/ui-kit/soft-ui-design-system">Newspaper Agency</a>
            </h1>
            <p class="lead text-white text-bold mt-3">
              All that you should know about the world in a few words!
            </p>
          </div>
        </div>
      </div>
      <div class="position-absolute w-100 z-index-1 bottom-0">
        <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 24 150 40" preserveAspectRatio="none" shape-rendering="auto">
          <defs>
            <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z" />
          </defs>
          <g class="moving-waves">
            <use xlink:href="#gentle-wave" x="48" y="-1" fill="rgba(255,255,255,0.40" />
            <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(255,255,255,0.35)" />
            <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(255,255,255,0.25)" />
            <use xlink:href="#gentle-wave" x="48" y="8" fill="rgba(255,255,255,0.20)" />
            <use xlink:href="#gentle-wave" x="48" y="13" fill="rgba(255,255,255,0.15)" />
            <use xlink:href="#gentle-wave" x="48" y="16" fill="rgba(255,255,255,0.95" />
          </g>
        </svg>
      </div>
    </div>
  </header>
  <section class="pt-3 pb-4" id="count-stats">
    <div class="container">
      <div class="row">
        <div class="col-lg-9 z-index-2 border-radius-xl mt-n10 mx-auto py-3 blur shadow-blur">
          <div class="row">
            <div class="col-md-4 position-relative">
              <div class="p-3 text-center">
                <h1 class="text-gradient text-info"><span id="state1" countTo="{{ num_newspapers }}">0</span>+</h1>
                <h5 class="mt-3">Newspapers</h5>
                <p class="text-sm">Not just words, but something more...</p>
              </div>
              <hr class="vertical dark">
            </div>
            <div class="col-md-4 position-relative">
              <div class="p-3 text-center">
                <h1 class="text-gradient text-info"> <span id="state2" countTo="{{ num_topics }}">0</span>+</h1>
                <h5 class="mt-3">Topics</h5>
                <p class="text-sm">The hottest and most important spheres of modern conversations</p>
              </div>
              <hr class="vertical dark">
            </div>
            <div class="col-md-4">
              <div class="p-3 text-center">
                <h1 class="text-gradient text-info" id="state3" countTo="{{ num_redactors }}">0</h1>
                <h5 class="mt-3">Redactors</h5>
                <p class="text-sm">The beautiful community of real professionals and just people who love their job!</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}

  <script src="{{ ASSETS_ROOT }}/js/plugins/countup.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/rellax.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/tilt.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>

  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTTfWur0PDbZWPr7Pmq8K3jiDp0_xUziI"></script>
  <script src="{{ ASSETS_ROOT }}/js/soft-design-system.min.js?v=1.0.1" type="text/javascript"></script>
  <script type="text/javascript">
    if (document.getElementById('state1')) {
      const countUp = new CountUp('state1', document.getElementById("state1").getAttribute("countTo"));
      if (!countUp.error) {
        countUp.start();
      } else {
        console.error(countUp.error);
      }
    }
    if (document.getElementById('state2')) {
      const countUp1 = new CountUp('state2', document.getElementById("state2").getAttribute("countTo"));
      if (!countUp1.error) {
        countUp1.start();
      } else {
        console.error(countUp1.error);
      }
    }
    if (document.getElementById('state3')) {
      const countUp2 = new CountUp('state3', document.getElementById("state3").getAttribute("countTo"));
      if (!countUp2.error) {
        countUp2.start();
      } else {
        console.error(countUp2.error);
      };
    }
  </script>

{% endblock javascripts %}


templates/newspaper/newspaper_confirm_delete.html
{% extends "base-presentation.html" %}

{% block content %}
  <div class="container py-2">
    <h1>Delete?</h1>
    <p>
      Are you sure you want to delete ({{ newspaper.title }})?
    </p>
    <form action="" method="POST">
      {% csrf_token %}
      <input type="submit" value="Yes, delete" class="btn btn-danger" />
      <a href="{% url 'newspaper:newspaper-detail' pk=newspaper.id %}"><label>
        <input value="No, cancel" class="btn btn-success" />
      </label></a>
    </form>
  </div>
{% endblock %}

templates/newspaper/newspaper_detail.html
{% extends "base-presentation.html" %}

{% block content %}
  <div class="container py-2">
    <h2>
      <strong>
        {{ newspaper.title }}
      </strong>
    </h2>
    <p><strong>Topic:</strong> {{ newspaper.topic.name}}</p>
    <h2>
      Context:
    </h2>
    <p>
      {{ newspaper.content }}
    </p>
    <h3>
      Publishers

      {% if newspaper in user.newspapers.all %}
        <a href="{% url 'newspaper:toggle-newspaper-assign' pk=newspaper.id %}" class="btn btn-danger link-to-page mb-0 me-1">
          Delete me from this news
        </a>
      {% else %}
        <a href="{% url 'newspaper:toggle-newspaper-assign' pk=newspaper.id %}" class="btn d-inline-flex btn-success link-to-page mb-0 me-1">
          Assign me to this news
        </a>
      {% endif %}

    </h3>
    <hr>
    <ul>
      {% for publisher in newspaper.publisher.all %}
        <p class="text-muted"><strong>Id:</strong> {{ publisher.id }}</p>
        <li><strong>Username: </strong> {{ publisher.username }} ({{ publisher.first_name }} {{ publisher.last_name }})
          - {{ publisher.years_of_experience }} experience years</li>
        <br>
      {% endfor %}
    </ul>

    <a href="{% url 'newspaper:newspaper-delete' pk=newspaper.id %}" class="btn btn-danger link-to-page">
      Delete
    </a>

    <a href="{% url 'newspaper:newspaper-update' pk=newspaper.id %}" class="btn btn-info link-to-page">
      Update
    </a>
  </div>
{% endblock %}

templates/newspaper/newspaper_form.html
{% extends "base-presentation.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container py-2">
    <h1>{{ object|yesno:"Update,Create" }} news</h1>
    <form action="" method="post" novalidate>
      {% csrf_token %}
      {{ form|crispy }}

      <input type="submit" value="Submit" class="btn btn-success">
    </form>
  </div>
{% endblock %}

templates/newspaper/newspaper_list.html
{% extends "base-presentation.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container py-2">
    <h1 class="d-flex justify-content-between align-items-center">
      Newspapers List
      <a href="{% url 'newspaper:newspaper-create' %}" class="btn btn-info link-to-page btn-round mb-0 me-1">
        Add
      </a>
    </h1>

    <section class="py-1">
      <div class="container">
        <div class="row justify-content-between py-3">
          <div class="col-lg-4 mx-auto">
            <form action="" method="get" class="form-inline">
              <div class="input-group">
                {{ search_form|crispy }}
                <div class="input-group-append">
                  <button type="submit" class="btn btn-secondary">
                    <i class="fa fa-search"></i>
                  </button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>

  <br>

  {% if newspaper_list %}
    <ul>
      {% for news in newspaper_list %}
        <li>
          <a href="{% url "newspaper:newspaper-detail" pk=news.id %}">{{ news.title }}</a>
          ({{ news.topic.name }})
        </li>
      {% endfor %}
    </ul>
    </ul>
  {% else %}
    <p>There are no news in newspaper</p>
  {% endif %}
  </div>
{% endblock %}

templates/newspaper/redactor_confirm_delete.html
{% extends "base-presentation.html" %}

{% block content %}
  <div class="container py-2">
    <h1>Delete?</h1>
    <p>
      Are you sure you want to delete ({{ redactor.username }})?
    </p>
    <form action="" method="POST">
      {% csrf_token %}
      <input type="submit" value="Yes, delete" class="btn btn-danger" />
      <a href="{% url 'newspaper:redactor-detail' pk=redactor.id %}"><label>
        <input value="No, cancel" class="btn btn-success" />
      </label></a>
    </form>
  </div>
{% endblock %}

templates/newspaper/redactor_detail.html
{% extends "base-presentation.html" %}

{% block content %}
  <div class="container py-2">
    <h1>
      Username: {{ redactor.username }}
      <a href="{% url 'newspaper:redactor-delete' pk=redactor.id %}" class="btn btn-danger link-to-page">
        Delete
      </a>

      <a href="{% url 'newspaper:redactor-update' pk=redactor.id %}" class="btn btn-info link-to-page">
        Update info
      </a>
    </h1>

    <p><strong>First name:</strong> {{ redactor.first_name }}</p>
    <p><strong>Last name:</strong> {{ redactor.last_name }}</p>
    <p><strong>Email:</strong> {{ redactor.email }}</p>
    <p><strong>Years of experience:</strong> {{ redactor.years_of_experience }}</p>
    <p><strong>Is staff:</strong> {{ redactor.is_staff }}</p>

    <div class="ml-3">
      <h3>News</h3>

      {% for news in redactor.newspapers.all %}
          <hr>
          <p><strong>Title:</strong> {{ news.title }}</p>
          <p><strong>Topic:</strong> {{ news.topic.name }}</p>
          <p class="text-muted"><strong>Id:</strong> {{news.id}}</p>

      {% empty %}
        <p>No news!</p>
      {% endfor %}
    </div>
  </div>
{% endblock %}

templates/newspaper/redactor_form.html
{% extends "base-presentation.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container py-2">
    <h1>{{ object|yesno:"Update,Create" }} redactor</h1>
    <form action="" method="post" novalidate>
      {% csrf_token %}
      {{ form|crispy }}

      <input type="submit" value="Submit" class="btn btn-success">
    </form>
  </div>
{% endblock %}

templates/newspaper/redactor_list.html
{% extends "base-presentation.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container py-2">
    <h1 class="d-flex justify-content-between align-items-center">
      Redactors List
      <a href="{% url 'newspaper:redactor-create' %}" class="btn btn-info link-to-page btn-round mb-0 me-1">
        Add
      </a>
    </h1>

    <section class="py-1">
      <div class="container">
        <div class="row justify-content-between py-3">
          <div class="col-lg-4 mx-auto">
            <form action="" method="get" class="form-inline">
              <div class="input-group">
                {{ search_form|crispy }}
                <div class="input-group-append">
                  <button type="submit" class="btn btn-secondary">
                    <i class="fa fa-search"></i>
                  </button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>

    <br>
    {% if redactor_list %}
    <table class="table container">
      <tr>
        <th>ID</th>
        <th>Username</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Experience years</th>
      </tr>
    {% for redactor in redactor_list %}
      <tr>
        <td>{{ redactor.id }}</td>
        <td><a style="color: blue" href="{{ redactor.get_absolute_url }}">{{ redactor.username }} {% if user == redactor %} (Me){% endif %}</a></td>
        <td>{{ redactor.first_name }}</td>
        <td>{{ redactor.last_name }}</td>
        <td>{{ redactor.years_of_experience }}</td>
      </tr>
    {% endfor %}

    </table>
    {% else %}
      <p class="container">There are no redactors in the agency.</p>
    {% endif %}
  </div>
{% endblock %}

templates/newspaper/topic_confirm_delete.html
{% extends "base-presentation.html" %}

{% block content %}
  <div class="container py-2">
    <h1>Delete?</h1>
    <p>If you delete ({{ topic.name }})
      this also deletes all related news!
      Are you sure you want to delete?
    </p>
    <form action="" method="POST">
      {% csrf_token %}
      <input type="submit" value="Yes, delete" class="btn btn-danger" />
      <a href="{% url 'newspaper:topic-list'%}"><label>
        <input value="No, cancel" class="btn btn-success" />
      </label></a>
    </form>
  </div>
{% endblock %}

templates/newspaper/topic_form.html
{% extends "base-presentation.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container py-2">
    <h1>{{ object|yesno:"Update,Create" }} topic</h1>
    <form action="" method="post" novalidate>
      {% csrf_token %}
      {{ form|crispy }}

      <input type="submit" value="Submit" class="btn btn-success">
    </form>
  </div>
{% endblock %}

templates/newspaper/topic_list.html
{% extends "base-presentation.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container py-2">
    <h1 class="d-flex justify-content-between align-items-center">
      Topic List
      <a href="{% url 'newspaper:topic-create' %}" class="btn btn-info link-to-page btn-round mb-0 me-1">
        Add
      </a>
    </h1>

    <section class="py-1">
      <div class="container">
        <div class="row justify-content-between py-3">
          <div class="col-lg-4 mx-auto">
            <form action="" method="get" class="form-inline">
              <div class="input-group">
                {{ search_form|crispy }}
                <div class="input-group-append">
                  <button type="submit" class="btn btn-secondary">
                    <i class="fa fa-search"></i>
                  </button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>

    <br>

    {% if topic_list %}
      <table class="table">
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Update</th>
          <th>Delete</th>
        </tr>

        {% for topic in topic_list %}
          <tr>
            <td>
                {{ topic.id }}
            </td>
            <td>
                {{ topic.name }}
            </td>
            <td>
                <a href="{% url 'newspaper:topic-update' pk=topic.id %}" style="color: green">
                  Update
                </a>
              </td>
              <td>
                <a style="color: red"
                  href="{% url 'newspaper:topic-delete' pk=topic.id %}">
                  Delete
                </a>
              </td>
          </tr>
        {% endfor %}
      </table>

    {% else %}
        <p>There are no topics here.</p>
    {% endif %}
  </div>
{% endblock %}